name: ci_validation 

on:
  push:
    branches:
    - main
    paths:
      - 'notebooks/**.ipynb'
env: 
  WEBBPSF_PATH: $PWD/data/webbpsf-data
  PYSYN_CDBS: $PWD/grp/redcat/trds/

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2 ## needed for caching
      with:
        python-version: 3.8.12
        cache: 'pip'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        #conda env update --file CIenvironment.yml --name base
        pip install -r requirements.txt
        pip install pytest
        pip install nbval
        pip install nbconvert
        
    - name: Gather changed notebooks
      id: changed-files
      uses: tj-actions/changed-files@v18.4
      with:
        files: |
          **/*.ipynb

    - name: Valdiating changed notebooks
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was updated, validating notebook"
          run: | 
            pytest --nbval $file
        done
        
    - name: Executing changed notebooks
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was updated, executing notebook"
          run: | 
            jupyter nbconvert --template classic --to html --execute $file
        done

        
#    - name: Execute notebooks
#      run: |
#        find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template classic --to html --execute {} \; 
#    - name: Test with pytest
#      run: |
#        pytest --nbval
